Add functionality to load photoscans
OpenwaterHealth/OpenLIFU-python pull request #186
Opened 2024-12-12 22:14 UTC by sadhana-r

Closes #180

2025-01-21 20:19 UTC, ebrahimebrahim requested changes
Nice work, some changes/additions requested where I spotted things.

For where to put the photoscan.py module, I think since it doesn't belong in any of the current folders you can put at at the top level, similar to `geo.py`. If it ever gets a friend that belongs with it in the future then we can create a new folder for them. What do you think of that?

2025-01-21 20:19 UTC, ebrahimebrahim commented on src/openlifu/db/photoscan.py
> +    valid_suffixes = ['.g', '.obj', '.stl', '.ply', '.vtk', '.vtp']
A more pretty approach could be to replace `valid_suffixes` by 

```
suffix_to_reader_dict = {
    '.ply' : vtk.vtkPLYReader,
    '.vtp' : vtk.vtkXMLPolyDataReader,
    # etc.
}
```

and then you can be like `reader = suffix_to_reader_dict[ext]()` instead having so many `elif`s

2025-01-21 20:19 UTC, ebrahimebrahim commented on src/openlifu/db/photoscan.py
> +    #new_rgb_data = np.flipud(new_rgb_data) # To look like blender format upon loading. Image is instead flipped in texture module.
blender format?

2025-01-21 20:19 UTC, ebrahimebrahim commented on src/openlifu/db/photoscan.py
> +def convert_numpy_to_vtkimage(image_numpy):
This function could use a docstring and type annotations. What is the expected shape of `image_numpy`? it's only for 2D images right?

I feel this function could use a unit test. The test could create a tiny 2D numpy array with some known values, run it through this function to get a vtk image, and then just make sure that the two agree at some location where the value is known

2025-01-21 20:19 UTC, ebrahimebrahim commented on src/openlifu/db/photoscan.py
> +def convert_between_ras_and_lps(mesh):
this function needs type annotations and should be unit tested

2025-01-22 18:10 UTC, sadhana-r commented on src/openlifu/db/photoscan.py
> +    #new_rgb_data = np.flipud(new_rgb_data) # To look like blender format upon loading. Image is instead flipped in texture module.
I'll remove this line. The texture image needs to be flipped before it is applied to the model. When testing this, I was comparing this functionality to the the image when loaded using blender. But Sam's code for applying the texture in Slicer includes the image flip so the image does not need to get flipped here.

2025-01-27 18:55 UTC, ebrahimebrahim approved these changes
Great work and I love the new unit tests -- thank you!

2025-01-27 19:40 UTC, merged