Raise exception in unimplemented db methods
OpenwaterHealth/OpenLIFU-python pull request #81
Opened 2024-07-10 15:19 UTC by ebrahimebrahim

Issue #79

2024-07-11 14:00 UTC, peterhollender commented
One of the reasons for attaching the Volume was that I really want the database i/o to live at the periphery of the code. The Database object hasn't been typically passed around to other methods, as a `Session` object was sort of "fully-hydrated". However, I think it could work in this instance, because I did later introduce the concept of a Scene, which is a spatially-oriented view of the data from a Session. It could be in the conversion of Session to Scene that the volume is loaded. In the Python code, `Session` is defined in the `db` module already, so it makes me a little more comfortable having that operation involve the Database object

2024-07-11 16:25 UTC, ebrahimebrahim commented
> One of the reasons for attaching the Volume was that I really want the database i/o to live at the periphery of the code. The Database object hasn't been typically passed around to other methods, as a `Session` object was sort of "fully-hydrated". However, I think it could work in this instance, because I did later introduce the concept of a Scene, which is a spatially-oriented view of the data from a Session. It could be in the conversion of Session to Scene that the volume is loaded. In the Python code, `Session` is defined in the `db` module already, so it makes me a little more comfortable having that operation involve the Database object

That makes sense. In a way, the internals of `Session` and `Subject` are part of that database i/o periphery.

Besides volumes, another reason for passing the Database along when constructing a Session is to allow for it to look up the Transducer. The json file defining a Session only has a _reference_ to a transducer, and without the Database object the `Session.from_file` method wouldn't know how to find the actual transducer definition file.

2024-07-11 16:31 UTC, peterhollender commented
> > One of the reasons for attaching the Volume was that I really want the database i/o to live at the periphery of the code. The Database object hasn't been typically passed around to other methods, as a `Session` object was sort of "fully-hydrated". However, I think it could work in this instance, because I did later introduce the concept of a Scene, which is a spatially-oriented view of the data from a Session. It could be in the conversion of Session to Scene that the volume is loaded. In the Python code, `Session` is defined in the `db` module already, so it makes me a little more comfortable having that operation involve the Database object
> 
> That makes sense. In a way, the internals of `Session` and `Subject` are part of that database i/o periphery.
> 
> Besides volumes, another reason for passing the Database along when constructing a Session is to allow for it to look up the Transducer. The json file defining a Session only has a _reference_ to a transducer, and without the Database object the `Session.from_file` method wouldn't know how to find the actual transducer definition file.

Yeah, that tracks. In the MATLAB version, there is no `Session.from_file`, as it relies on the `Database.load_session` to load the session data from disk and hydrate it with the transducer and volume.

2024-08-07 16:31 UTC, ebrahimebrahim commented
I added the example database folder as  a resource to be used for unit testing. I removed any large files from there and shrank the example volume so this should not bloat the repo

2024-08-08 17:16 UTC, peterhollender requested changes
We should strip back the verasonics and M2 stuff from the example repository
Edit: didn't add the comments, so this is a duplicate review

2024-08-08 17:18 UTC, peterhollender requested changes
We should strip back the verasonics and M2 stuff from the example repository

2024-08-08 17:18 UTC, peterhollender commented on tests/resources/example_db/systems/connected_system.txt
I don't think we need this file, as it is created once the user has selected a connected system. The system logic will probably get streamlined as we deprecate Verasonics support, anyway.

2024-08-08 17:18 UTC, peterhollender commented on tests/resources/example_db/systems/systems.json
This should either be an empty list, or we should create a generic test system that doesn't depend on the verasonics matlab code.

2024-08-08 17:18 UTC, peterhollender commented on tests/resources/example_db/systems/vantage/vantage.json
This shouldn't be included, or we should make a generic system.

2024-08-08 17:18 UTC, peterhollender commented on tests/resources/example_db/transducers/M2/M2.json
This is a specific transducer, and should be excluded

2024-08-08 17:18 UTC, peterhollender commented on tests/resources/example_db/transducers/transducers.json
this should only have the example transducer.

2024-08-15 13:37 UTC, peterhollender approved these changes

2024-08-15 14:06 UTC, merged